### ISSUE TITLE
Precompilation fails when using C# 7.0

### ISSUE THREAD

**Issue by niklaslundberg** [aspnet/MvcPrecompilation#105]
When using precompilation in a web project

- Microsoft.NET.Sdk.Web
- TargetFramework=netcoreapp1.1
- MvcRazorCompileOnPublish=true
- PreserveCompilationContext=true
- LangVersion=7
- NuGet package Microsoft.AspNetCore.Mvc.Razor.ViewCompilation 1.1.0

then it fails throwing an exception:

```
dotnet exec --runtimeconfig "C:\Projects\MyProject\bin\debug\netcoreapp1.1\MyWebProject.runtimeconfig.json" --depsfile "C:\Projects\MyProject\bin\debug\netcoreapp1.1\MyWebProject.deps.json" "C:\Users\MyUser\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0\build\netcoreapp1.1\../../lib/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\debug\netcoreapp1.1\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"
Specified argument was out of the range of valid values.
Parameter name: version
at Microsoft.CodeAnalysis.CSharp.CSharpParseOptions.WithLanguageVersion(LanguageVersion version)
at Microsoft.AspNetCore.Mvc.Razor.Internal.DependencyContextRazorViewEngineOptionsSetup.SetParseOptions(RazorViewEngineOptions options, CompilationOptions compilationOptions)
at Microsoft.AspNetCore.Mvc.Razor.Internal.DependencyContextRazorViewEngineOptionsSetup.Configure(RazorViewEngineOptions options)
at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
at Microsoft.Extensions.Options.OptionsCache`1.get_Value()
at Microsoft.AspNetCore.Mvc.Razor.Internal.DefaultRazorViewEngineFileProviderAccessor..ctor(IOptions`1 optionsAccessor)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.<>c.<AddRazorViewEngineServices>b__5_0(IServiceProvider serviceProvider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProvider.<>c__DisplayClass16_0.<RealizeService>b__0(ServiceProvider provider)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.MvcServiceProvider..ctor(String projectPath, String applicationName, String contentRoot, String configureCompilationType)
at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.Execute()
at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompilationApplication.Execute(String[] args)
```

**Comment by davidfowl** [comment]
Did you update the roslyn package?

**Comment by niklaslundberg** [comment]
I've also installed Microsoft.Net.Compilers 2.0.1, no difference. Also tried with Microsoft.CodeDom.Providers.DotNetCompilerPlatform 1.0.3.

**Comment by davidfowl** [comment]
Unfortunately, those were both the wrong packages to install. You need to update `Microsoft.CodeAnalysis.CSharp` to 2.0.0

**Comment by niklaslundberg** [comment]
With NuGet 4.0 and transitive dependencies it makes it hard to find out that there are newer version. Visual Studio 2017 does not show updates to packages unless they are direct dependencies. 

Adding Microsoft.CodeAnalysis.CSharp to 2.0.0 solved my issue.

**Comment by pranavkm** [comment]
Btw, Razor does not support C# 7.0. There's a work item to address this - https://github.com/aspnet/Razor/issues/1046. Changing the language version in the compilation isn't necessarily going to be sufficient to upgrade it.
