### ISSUE TITLE
Undo the workaround of publishing refs

### ISSUE THREAD

**Issue by kichalla** [aspnet/MvcPrecompilation#115]
To unblock the build following commit was made to fix the below error in CI:

**Error**
```
[08:10:57]	        dotnet stderr: Unhandled Exception: System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.AspNetCore.Mvc.Razor.Compilation.MetadataReferenceFeatureProvider.PopulateFeature(IEnumerable`1 parts, MetadataReferenceFeature feature)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.GetCompilationReferences()
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.AspNetCore.Mvc.Razor.Internal.RazorReferenceManager.get_CompilationReferences()
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.MvcRazorMvcCoreBuilderExtensions.<>c__DisplayClass5_0.<AddRazorViewEngineServices>b__1(IRazorEngineBuilder b)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.AspNetCore.Razor.Language.RazorEngine.Create(Action`1 configure)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitClosedIEnumerable(ClosedIEnumerableCallSite closedIEnumerableCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.AspNetCore.Builder.MvcApplicationBuilderExtensions.UseMvc(IApplicationBuilder app, Action`1 configureRoutes)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr: --- End of stack trace from previous location where exception was thrown ---
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
[08:10:57]	  warn: Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer[0]
[08:10:57]	        dotnet stderr:    at ApplicationWithConfigureStartup.Program.Main(String[] args)
```

**Comment by kichalla** [comment]
Commit: 69e2fa82eb719012196ca035518ce7d96546f733

cc @pranavkm

**Comment by pranavkm** [comment]
Reverted in https://github.com/aspnet/MvcPrecompilation/commit/6b96a38dc82f5161a8efef8dfc2fa672b5c09a5c
