### ISSUE TITLE
View Compilation not working when using --manifest

### ISSUE THREAD

**Issue by rynowak** [aspnet/MvcPrecompilation#123]
Repro steps:

clone aspnet/JitBench
git checkout rel/2.0.0-preview1
`$env:MvcRazorCompileOnPublish="true"`
`.\appveyor.ps1`

I get an error like this: 
```
  MusicStore -> C:\Users\rynowak\git\aspnet\JitBench\src\MusicStore\bin\Release\netcoreapp2.0\MusicStore.dll
  One or more errors occurred. (Cannot find assembly file for package System.Data.SqlClient at 'C:\Users\rynowak\git\asp
net\JitBench\.store\x64\netcoreapp2.0\system.data.sqlclient/4.4.0-preview1-25229-02\ref/netstandard2.0/System.Data.SqlCl
ient.dll') (Cannot find assembly file for package System.Data.SqlClient at 'C:\Users\rynowak\git\aspnet\JitBench\.store\
x64\netcoreapp2.0\system.data.sqlclient/4.4.0-preview1-25229-02\ref/netstandard2.0/System.Data.SqlClient.dll') (Cannot f
ind assembly file for package System.Data.SqlClient at 'C:\Users\rynowak\git\aspnet\JitBench\.store\x64\netcoreapp2.0\sy
stem.data.sqlclient/4.4.0-preview1-25229-02\ref/netstandard2.0/System.Data.SqlClient.dll') (Cannot find assembly file fo
r package System.Data.SqlClient at 'C:\Users\rynowak\git\aspnet\JitBench\.store\x64\netcoreapp2.0\system.data.sqlclient/
4.4.0-preview1-25229-02\ref/netstandard2.0/System.Data.SqlClient.dll')
     at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Bool
ean stopOnFirstFailure)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parall
elOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, Cancell
ationToken cancelToken, Exception otherException)
     at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parall
elOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
     at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Act
ion`1 body)
     at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.GenerateCode()
     at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.Execute()
     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
     at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompilationApplication.Execute(String[] args)
C:\Users\rynowak\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0-preview2-24898\build\netcoreapp2.0
\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(26,5): error MSB3073: The command "dotnet exec --runtimeconfig "
C:\Users\rynowak\git\aspnet\JitBench\src\MusicStore\bin\Release\netcoreapp2.0\MusicStore.runtimeconfig.json" --depsfile
"C:\Users\rynowak\git\aspnet\JitBench\src\MusicStore\bin\Release\netcoreapp2.0\MusicStore.deps.json" "C:\Users\rynowak\.
nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\2.0.0-preview2-24898\build\netcoreapp2.0\Microsoft.AspNetC
ore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exit
ed with code 1. [C:\Users\rynowak\git\aspnet\JitBench\src\MusicStore\MusicStore.csproj]
```

**Comment by rynowak** [comment]
So the issue here is that having `DOTNET_SHARED_STORE` to a package store is causing this. I'm not sure if this means that users won't hit this. It needs more investigation from someone familar with this.

**Comment by pranavkm** [comment]
I can't actually run the script - R2R-gening hangs after a while. I'm going to close this for now. We can re-open if this you continue seeing the error in the repo once you get it to work.

**Comment by pranavkm** [comment]
Verified and this works without issues now.
