### ISSUE TITLE
[Patch 1.1.3] : Flaky test ViewCompilationOptionsTest.PublishingWithOption_AllowsPublishingRefAssemblies

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#195]
```
System.InvalidOperationException : No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.ViewCompilationOptionsTest.PublishingWithOption_AllowsPublishingRefAssemblies(RuntimeFlavor flavor) in C:\b\w\d6337ac2abf63a4b\.repositories\MvcPrecompilation\test\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests\ViewCompilationOptionsTest.cs:line 55
```

**Comment by pranavkm** [comment]
cc @Eilon

**Comment by pranavkm** [comment]
Skipped in https://github.com/aspnet/MvcPrecompilation/commit/5a7e4b83cbd6d7d24c05516c00e84923f17a8366
