### ISSUE TITLE
Functional tests hang with latest runtime

### ISSUE THREAD

**Issue by JunTaoLuo** [aspnet/MvcPrecompilation#210]
I have disabled the functional tests to unblock the build in https://github.com/aspnet/MvcPrecompilation/commit/61a9475b573e18b661dc4bb257f8591cae7f44f4 which needs to be reverted.

The error seems to stem from redirection of StandError not working as expected on the latest 1.1 runtime, see http://aspnetci/viewLog.html?buildId=343743&tab=buildResultsDiv&buildTypeId=Releases_Ubuntu1404:
```
[16:57:42] :			 [xunit-test] Test run for /datadrive/teamcity/w/d6337ac2abf63a4b/.repositories/MvcPrecompilation/test/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests/bin/Release/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.FunctionalTests.dll(.NETCoreApp,Version=v1.1)
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test] Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test] Copyright (c) Microsoft Corporation.  All rights reserved.
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test] 
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test] Starting test execution, please wait...
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test] 
[16:57:42] :			 [xunit-test]   
16:57:42] :			 [xunit-test] Unhandled Exception: Process with an Id of 64156 is not running.
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test] System.InvalidOperationException: StandardError has not been redirected.
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test]    at System.Diagnostics.Process.get_StandardError()
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test]    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.<>c__DisplayClass9_0.<SetupChannel>b__0(Process process)
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test]    at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Helpers.ProcessHelper.<>c__DisplayClass0_0.<LaunchProcess>b__0(Object sender, EventArgs args)
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test]    at System.Diagnostics.Process.OnExited()
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test]    at System.Diagnostics.Process.RaiseOnExited()
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test]    at System.Diagnostics.Process.CompletionCallback(Object context, Boolean wasSignaled)
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
[16:57:42] :			 [xunit-test]   
[16:57:42] :			 [xunit-test]    at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(Object state, Boolean timedOut)
[16:57:43] :			 [xunit-test]   
[16:57:43] :			 [xunit-test] 
[16:57:43] :			 [xunit-test]   
[16:57:43] :			 [xunit-test] 
[16:57:43] :			 [xunit-test]   
[16:57:43] :			 [xunit-test]   fail: Exit code 1 from dotnet
[16:57:43] :			 [xunit-test]   fail: Stack trace: 
[16:57:43] :			 [xunit-test]     at View9748619b20b446e0b01ba816599857e6.Dotnet (System.String command, System.String dotnetDir) <0x41eb91c0 + 0x00833> in <filename unknown>:0 
[16:57:43] :			 [xunit-test]     at View9748619b20b446e0b01ba816599857e6.DotnetTest (System.String projectFile, System.String configuration, System.String test_options, System.String framework) <0x41eb8f10 + 0x001cb> in <filename unknown>:0 
[16:57:44] :			 [xunit-test] /datadrive/teamcity/w/d6337ac2abf63a4b/targets/BuildRepositories.targets(100,5): error MSB3073: The command "./build.sh verify" exited with code 1. [/datadrive/teamcity/w/d6337ac2abf63a4b/makefile.proj]
[16:57:44] :			 [xunit-test] Done Building Project "/datadrive/teamcity/w/d6337ac2abf63a4b/makefile.proj" (_Build-Repo target(s)) -- FAILED.
[16:57:44] :			 [xunit-test] Done Building Project "/datadrive/teamcity/w/d6337ac2abf63a4b/makefile.proj" (BuildRepositories target(s)) -- FAILED.
[16:57:44] :			 [xunit-test] 
[16:57:44] :			 [xunit-test] Build FAILED.
```

cc @Eilon @pranavkm

**Comment by pranavkm** [comment]
Is this in the 1.1 patch branch?

**Comment by JunTaoLuo** [comment]
Yes

**Comment by JunTaoLuo** [comment]
Figured it out

**Comment by pranavkm** [comment]
What was the issue?
