### ISSUE TITLE
Flaky test: PublishingWithOption_SkipsPublishingPrecompiledDll

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/MvcPrecompilation#254]
This test [fails](http://aspnetci/viewLog.html?buildId=431374&buildTypeId=Lite_MvcPrecompilation) occasionally with the following error:
```
System.Exception : dotnet publish exited with exit code : 1
   at Microsoft.AspNetCore.Server.IntegrationTesting.ApplicationDeployer.DotnetPublish(String publishRoot)
   at Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer.DeployAsync() in C:\b\w\16b675287913954b\test\FunctionalTests\Infrastructure\PublishOnlyDeployer.cs:line 33
   at FunctionalTests.ApplicationTestFixture.<CreateDeploymentAsync>d__19.MoveNext() in C:\b\w\16b675287913954b\test\FunctionalTests\Infrastructure\ApplicationTestFixture.cs:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FunctionalTests.CopyBuildOutputToPublishDirectory_CoreCLR.<PublishingWithOption_SkipsPublishingPrecompiledDll>d__4.MoveNext() in C:\b\w\16b675287913954b\test\FunctionalTests\CoreCLRTests\CopyBuildOutputToPublishDirectory_CoreCLR.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
------- Stdout: -------
| TestLifetime Information: Starting test PublishingWithOption_SkipsPublishingPrecompiledDll
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: Deploying [Variation] :: ServerType=Kestrel, Runtime=CoreClr, Arch=x64, BaseUrlHint=, Publish=True
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: Removing environment variable ASPNETCORE_ENVIRONMENT
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: SET DOTNET_CLI_TELEMETRY_OPTOUT=1
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: SET SolutionConfiguration=Release
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: SET CopyBuildOutputToPublishDirectory=false
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: Executing command dotnet publish  --output "C:\b\t\buildTmp\7ea75773-e8e4-47b2-a998-5c330a2dd275" --framework netcoreapp2.0 --configuration Release --no-restore 
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: dotnet-publish stdout: Microsoft (R) Build Engine version 15.7.66.2115 for .NET Core
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: dotnet-publish stdout: Copyright (C) Microsoft Corporation. All rights reserved.
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: dotnet-publish stdout:   You are working with a preview version of the .NET Core SDK. You can define the SDK version via a global.json file in the current project. More at https://go.microsoft.com/fwlink/?linkid=869452
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: dotnet-publish stdout:   SimpleApp -> C:\b\w\16b675287913954b\testapps\SimpleApp\bin\Release\netcoreapp2.0\SimpleApp.dll
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Information: dotnet-publish stdout: C:\b\w\16b675287913954b\src\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation\build\netstandard2.0\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(152,5): error MSB3491: Could not write lines to file "obj\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp". The process cannot access the file 'C:\b\w\16b675287913954b\testapps\SimpleApp\obj\Release\netcoreapp2.0\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp' because it is being used by another process. [C:\b\w\16b675287913954b\testapps\SimpleApp\SimpleApp.csproj]
| Microsoft.AspNetCore.Server.IntegrationTesting.PublishOnlyDeployer Error: dotnet publish exited with exit code : 1
| TestLifetime Information: Finished test PublishingWithOption_SkipsPublishingPrecompiledDll in 22.4625547s
```

Future instances of this error can be found [here](http://aspnetci/httpAuth/app/rest/builds?locator=tag:RspAccess,sinceDate:201710010T000000-0001&fields=build(startDate,buildTypeId,status,branchName,webUrl,tags)).

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, can you please investigate this one too? Thanks!

**Comment by ajaybhargavb** [comment]
83ebebcabc90783c7b45b006fd5b2a0ca3e62edc
