### ISSUE TITLE
Flaky test: Precompilation_WorksForSimpleApps

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/MvcPrecompilation#261]
This test [fails](http://aspnetci/viewLog.html?buildId=442325&buildTypeId=Lite_MvcTest) occasionally with the following error:

```
System.Exception : Command exited unexpectedly with exit code: 255
   at Microsoft.AspNetCore.Testing.TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.StartSelfHostAsync(Uri hintUrl)
   at Microsoft.AspNetCore.Server.IntegrationTesting.SelfHostDeployer.DeployAsync()
   at FunctionalTests.ApplicationTestFixture.CreateDeploymentAsync(ILoggerFactory loggerFactory) in C:\b\w\33bdfc1cae7b2a38\modules\MvcPrecompilation\test\FunctionalTests\Infrastructure\ApplicationTestFixture.cs:line 109
   at FunctionalTests.SimpleAppWithAssemblyRenameTest_CoreCLR.Precompilation_WorksForSimpleApps() in C:\b\w\33bdfc1cae7b2a38\modules\MvcPrecompilation\test\FunctionalTests\CoreCLRTests\SimpleAppWithAssemblyRenameTest_CoreCLR.cs:line 30
```

Future instances of this failure can be found [here](http://aspnetci/project.html?projectId=XPlat&testNameId=3727025192993549654&tab=testDetails).

**Comment by ajaybhargavb** [comment]
@pranavkm recently made a [change](https://github.com/aspnet/MvcPrecompilation/pull/272) to fix the way we deploy these tests (which is where the above failure happens). I checked the CI and this test hasn't failed since (past 20 days).
