### ISSUE TITLE
PreCompilation does not work for netcoreapp1.1

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/MvcPrecompilation#30]
When I target netcoreapp1.1 in my app and run precompilation it says,
```Text
Project 'C:\signoff\precomp' does not support framework: netcoreapp1.1
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileDispatchCommand.GetRuntimeContext()
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileDispatchCommand.Execute()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.Internal.PrecompilationApplication.Execute(String[] args)
```

It works fine for netcoreapp1.0 and net451.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/MvcPrecompilation/commit/d9140e97c9dd682e71e4d58affffb509b84ba0ec
