### ISSUE TITLE
Precompiled app not working for .NETFramework,Version=v4.6.1/win7-x86

### ISSUE THREAD

**Issue by dolly22** [aspnet/MvcPrecompilation#47]
Application published for full framework (net461), x86 target fails with BadImageFormatException

```
Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
   at BadImagePrecompilationRepro.Startup.ConfigureServices(IServiceCollection services) in c:\Users\dolet99\Documents\Visual Studio 2015\Projects\BadImagePrecompilationRepro\src\BadImagePrecompilationRepro\Startup.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at BadImagePrecompilationRepro.Program.Main(String[] args) in c:\Users\dolet99\Documents\Visual Studio 2015\Projects\BadImagePrecompilationRepro\src\BadImagePrecompilationRepro\Program.cs:line 14
```

It seems `lib/net451/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.exe` from Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design, 1.1.0-preview4-final package is forced to 64bit.

```
> corflags Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Design.exe
Microsoft (R) .NET Framework CorFlags Conversion Tool.  Version  4.6.1055.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Version   : v4.0.30319
CLR Header: 2.5
PE        : PE32+
CorFlags  : 0x9
ILONLY    : 1
32BITREQ  : 0
32BITPREF : 0
Signed    : 1
```

**Comment by pranavkm** [comment]
Thanks for catching this. @Eilon we'll have to compile the design tool for x86 (we do this in RazorTooling). Is this 1.1.1 worthy?

**Comment by Eilon** [comment]
@DamianEdwards thoughts on 1.1.1 for this? Seems reasonable, though I'm not sure how many people are running on 32bit these days.

**Comment by DamianEdwards** [comment]
It's a supported platform so our stuff should work there. I'm in favor of fixing this in 1.1.1

**Comment by Eilon** [comment]
@pranavkm any idea if we can just do AnyCPU for this or something? @bricelam had mentioned to me today that he did something similar for `dotnet ef` but I don't know how similar these issues are.

**Comment by pranavkm** [comment]
Let me give it a try. I'm not sure if `win7-any` is a valid runtime identifier.

**Comment by Eilon** [comment]
Feel free to sync with @bricelam to brainstorm on this.

**Comment by bricelam** [comment]
```XML
<PlatformTarget>AnyCPU </PlatformTarget>
```
I'm still trying to figure out how to disable Prefer 32-bit, but that may not be important here.

**Comment by Eilon** [comment]
This patch bug is **approved**. Please use the normal code review process w/ a PR and make sure the fix is in the correct branch, then close the bug and mark it as done.

**Comment by Eilon** [comment]
Taking this out of the "patch" list because we can just do it in the RTM build of this, which hasn't shipped yet.

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/MvcPrecompilation/issues/66

**Comment by yepeekai** [comment]
Using anycpu seems to fail.  The logic to use == x86 and != x86 has been removed and the target file uses $(PlatformTarget) directly which doesn't work for 'AnyCpu': 

"bin\Debug\net471\win-x64\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation-AnyCPU.exe" @"obj\Debug\net471\win-x64\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"
