### ISSUE TITLE
Update to netcoreapp1.2 once we figure out why referencing the newer project causes running the tool to fail

### ISSUE THREAD

**Issue by pranavkm** [aspnet/MvcPrecompilation#48]
Tracking CoreFx issue: https://github.com/dotnet/corefx/issues/14696.

Also need to re-enable tests once this issue is resolved.

**Comment by pranavkm** [comment]
Once we have a solution, https://github.com/aspnet/Coherence/commit/438590fbfd33996b26e19d4d7699e910e1950889 needs to be undone.

**Comment by pranavkm** [comment]
With no changes, (well the transitive dependencies targeting CoreFx 4.4.0-* packages), invoking `dotnet test` on any of the test projects in this repo is currently failing with:

```
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Xunit.Runner.DotNet.Program..ctor()
   at Xunit.Runner.DotNet.Program.Main(String[] args)
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.
```

Spoke with @Eilon offline and we decided it was ok to disable tests until we have a resolution for this.

**Comment by pranavkm** [comment]
Commit to be reverted to re-enable tests: https://github.com/aspnet/MvcPrecompilation/commit/f9efbf8e78c2e1a37d1de36debcaf9b9ea876aba

**Comment by pranavkm** [comment]
Switching to csproj resolved this issue. Addressed as part of the migration in https://github.com/aspnet/MvcPrecompilation/commit/3f5cce41c1ba11c4e574bd1ccc2464b4285621be
