### ISSUE TITLE
"Could not load file or assembly" exception when AssemblyName element specified in .csproj

### ISSUE THREAD

**Issue by kiwiant** [aspnet/MvcPrecompilation#92]
This works for a default project where the assembly name hasn't been specified. When the AssemblyName is specified the Precompilation fails with "Could not load file or assembly" as its trying to look for an assembly based on the project file name and not the assembly name.

Snippet from .csproj...

```xml
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <AssemblyTitle>AppName Web</AssemblyTitle>
    <AssemblyName>OrganisationName.AppName.Web</AssemblyName>
    <RootNamespace>OrganisationName.AppName.Web</RootNamespace>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <MvcRazorCompileOnPublish>true</MvcRazorCompileOnPublish>
  </PropertyGroup>
```

```
AppName.Web -> C:\Data\Projects\AppName\src\AppName.Web\bin\Release\netcoreapp1.1\OrganisationName.AppName.Web.dll
dotnet exec --runtimeconfig "C:\Data\Projects\AppName\src\AppName.Web\bin\Release\netcoreapp1.1\OrganisationName.AppName.Web.runtimeconfig.json" --depsfile "C:\Data\Projects\AppName\src\AppName.Web\bin\Release\netcoreapp1.1\OrganisationName.AppName.Web.deps.json" "C:\Users\User\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0-msbuild4-final\build\netcoreapp1.1\../../lib/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp1.1\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"
Could not load file or assembly 'AppName.Web, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.MvcServiceProvider.GetConfigureCompilationAction(String configureCompilationType)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.MvcServiceProvider..ctor(String projectPath, String applicationName, String contentRoot, String configureCompilationType)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompileRunCommand.Execute()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.Internal.PrecompilationApplication.Execute(String[] args)
C:\Users\User\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0-msbuild4-final\build\netcoreapp1.1\Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.targets(25,5): Error MSB3073: The command "dotnet exec --runtimeconfig "C:\Data\Projects\AppName\src\AppName.Web\bin\Release\netcoreapp1.1\OrganisationName.AppName.Web.runtimeconfig.json" --depsfile "C:\Data\Projects\AppName\src\AppName.Web\bin\Release\netcoreapp1.1\OrganisationName.AppName.Web.deps.json" "C:\Users\User\.nuget\packages\microsoft.aspnetcore.mvc.razor.viewcompilation\1.1.0-msbuild4-final\build\netcoreapp1.1\../../lib/netcoreapp1.1/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation.dll" @"obj\Release\netcoreapp1.1\microsoft.aspnetcore.mvc.razor.viewcompilation.rsp"" exited with code 1.

8>Publish failed due to build errors. Check the error list for more details.
========== Build: 7 succeeded or up-to-date, 0 failed, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by Eilon** [comment]
Yeah that sounds broken.

cc @ryanbrandenburg because you were also looking at some oddities with project name / assembly name / project *file* name etc.

**Comment by pranavkm** [comment]
Might be a dup of https://github.com/aspnet/Mvc/issues/5780 that was addressed by https://github.com/aspnet/MvcPrecompilation/pull/82

**Comment by Eilon** [comment]
@pranavkm can you confirm and if so, close as a dup?

**Comment by pranavkm** [comment]
Yup, this is a dup. @kiwiant you're welcome to try out a build of the package from our nightlies `https://dotnet.myget.org/f/aspnetcore-dev/api/v3/index.json`) where this issue has been fixed.

**Comment by kiwiant** [comment]
Thanks guys. Appreciate it.
